### ISSUE TITLE
Web3 Connection refused, help!

### ISSUE THREAD

**Issue by liuyuejiang** [simolus3/web3dart#32]
I run my smart contract on my MacBook, the IP address of my MacBook is 10.0.0.47, my flutter app runs on my phone in the same network 10.0.0.133, I can use the browser to access the web server on my MacBook, but when I tried to connect with my smart contract, it shows Connection refused, whatever I use private key or Json file, the result is the same.
Maybe this not the issue with web3dart, but can anybody help me with that, thanks a lot.

ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = 10.0.0.47, port = 45794

**Comment by liuyuejiang** [comment]
var privatekey = '0x6166244d506a4c1635e0a0723cda3780fa80462a869682xxxxxxxxxx';
    var apiUrl = "http://10.0.0.47:8545"; //Replace with your API

    var httpClient = new Client();
    var ethClient = new Web3Client(apiUrl, httpClient);
    // String data = await DefaultAssetBundle.of(context).loadString(
    //     "assets/web3/8acd17e6f4fef86fdf75078d179ec2612fb354ae.json");
    // final jsonResult = json.encode(data);

    // Wallet wallet = Wallet.fromJson(data, "aa");
    var credentials = Credentials.fromPrivateKeyHex(privatekey);

    // Credentials unlocked = wallet.credentials;
    EtherAmount balance = await ethClient.getBalance(credentials.address);
    print(balance.getValueInUnit(EtherUnit.ether));



I tried to use both methods. It didn't work.

**Comment by simolus3** [comment]
If you try something like 
```dart
var httpClient = new Client();
await httpClient.get('$apiUrl/');
```
before starting your `ethClient`. Does that also throw the exception? 
If so, you might be missing the internet permission in your Flutter app. Maybe [this](https://github.com/dart-lang/http/issues/185#issuecomment-468806547) helps?

**Comment by liuyuejiang** [comment]
It doesn't help when I add await httpClient.get('$apiUrl/');, the same exception.
This time I deployed my smart contract on ganache, when I tried to connect, it shows the same exception.

**Comment by liuyuejiang** [comment]
> If you try something like
> 
> ```dart
> var httpClient = new Client();
> await httpClient.get('$apiUrl/');
> ```
> 
> before starting your `ethClient`. Does that also throw the exception?
> If so, you might be missing the internet permission in your Flutter app. Maybe [this](https://github.com/dart-lang/http/issues/185#issuecomment-468806547) helps?

It doesn't help when I add await httpClient.get('$apiUrl/');, the same exception.
This time I deployed my smart contract on ganache, when I tried to connect, it shows the same exception.

**Comment by simolus3** [comment]
I don't think it's an issue with your operating system. Rather, the error indicates that your Flutter app is unable to reach the network,.

Are you on Android? If so, try adding `<uses-permission android:name="android.permission.INTERNET" /> ` to the `AndroidManifest.xml` in the `android/app` folder of your Flutter project.

**Comment by liuyuejiang** [comment]
I have already added the permission long long ago, the app can access the Internet well.
Do I need to provide other environment information?

**Comment by simolus3** [comment]
Hm, that's really weird.
But just to be sure, if you remove the `web3dart` related code of that snippet entirely and just try to make a request with the `http` package like this:
```dart
import "package:http/http.dart" as http;

await http.get("http://10.0.0.47:8545");
```
You do get the same problem, right?

I don't really get how your app can access the internet while still getting connection errors in `web3dart`. This library delegates all the work to the `Client()`, which is part of the `http` package. If you're making http requests elsewhere in your app, you're probably already using that package. It's weird how that works while there are errors in `web3dart`.

I'm not really familiar with MacOS unfortunately. I might be that there is a firewall blocking that port, even from the local network?

**Comment by liuyuejiang** [comment]
> Hm, that's really weird.
> But just to be sure, if you remove the `web3dart` related code of that snippet entirely and just try to make a request with the `http` package like this:
> 
> ```dart
> import "package:http/http.dart" as http;
> 
> await http.get("http://10.0.0.47:8545");
> ```
> 
> You do get the same problem, right?
> 
> I don't really get how your app can access the internet while still getting connection errors in `web3dart`. This library delegates all the work to the `Client()`, which is part of the `http` package. If you're making http requests elsewhere in your app, you're probably already using that package. It's weird how that works while there are errors in `web3dart`.
> 
> I'm not really familiar with MacOS unfortunately. I might be that there is a firewall blocking that port, even from the local network?

I do have these permissions, like:
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.hardware.location.gps" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

So, that's why confusing. I will try to use http tomorrow. Thank you, I will let you know.

**Comment by liuyuejiang** [comment]
I found the problem. In ganache, in the setting, the server's host name is 127.0.0.0 initially, I switch to 0.0.0.0 and it works well!!! Probably, for geth node, the problem is rpcdomain property.
Thank you so much! Finally, I spend a whole night to solve this problem.

**Comment by PeterTF656** [comment]
@simolus3 @liuyuejiang I am running into a very similar issue... In my case, my app runs fine on an ios simulator, but on an actual android device/emulator, it gives out ```E/flutter ( 6625): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = 0.0.0.0, port = 51300```, and I have added in the permission for android to access internet.

When I opened the dart dev tool, in the Network tab, the ws and http methods both showed pending. 

Any help is appreciated...

**Comment by simolus3** [comment]
Why would you connect to `0.0.0.0`? Surely there's no Ethereum node running on the actual emulator?

**Comment by PeterTF656** [comment]
> Why would you connect to `0.0.0.0`? Surely there's no Ethereum node running on the actual emulator?

Thank you sir for your quick reply. I used Ganache and I changed the server hostname to 0.0.0.0 - all interfaces

**Comment by simolus3** [comment]
Right, but the Android emulator will also setup a virtual network, so you can't reach your host through `0.0.0.0`. You can use `10.0.2.2` though, as explained [here](https://developer.android.com/studio/run/emulator-networking).

**Comment by PeterTF656** [comment]
> Right, but the Android emulator will also setup a virtual network, so you can't reach your host through `0.0.0.0`. You can use `10.0.2.2` though, as explained [here](https://developer.android.com/studio/run/emulator-networking).

Yes sir, It did work. Thank you! One more question, how about a real android device? Will it work with ```10.0.2.2```  Ganache?

**Comment by simolus3** [comment]
No, it wouldn't work on a real device. In that case you'd have to lookup the IP address of the host. Inside your local network it probably starts with `192.168`, so you could use that address for devices _inside your local network_.
